const projects = [
    {
        id: "portfolio",
        name: "Portfolio",
        description:
            "Portfolio personnel développé avec React, Vite et TailwindCSS.",
        image: "/img/portfolio.png",
        previewVideo: "/projects/portfolio-preview.mp4",
        status: "En ligne",
        tags: [
            { name: "react", color: "text-blue-400" },
            { name: "vite", color: "text-yellow-400" },
            { name: "tailwind", color: "text-cyan-400" },
        ],
        live_link: "https://mrkey2b.fr",
        source_code_link: "https://github.com/mrkey2b/mrkey2b.fr-portfolio",
        github: "https://github.com/mrkey2b/mrkey2b.fr-portfolio",
        gitlab: "",
        gitea: "",
        nexus: "",
    },
    {
        id: "pulsecv",
        name: "CV Builder ( PulseCV )",
        description:
            "SaaS de génération de CV avec export via job queue, partage sécurisé (token/expiration) et système de versioning.",
        image: "/img/pulsecv.png",
        previewVideo: "",
        status: "Déployé",
        tags: [
            { name: "react", color: "text-blue-400" },
            { name: "nextjs16", color: "text-blue-400" },
            { name: "tailwind", color: "text-cyan-400" },
            { name: "nodejs", color: "text-green-400" },
            { name: "supabase", color: "text-green-400" },
            { name: "deploy", color: "text-pink-400" },
        ],
        live_link: "https://cv.mrkey2b.fr",
        source_code_link: "https://github.com/mrkey2b/pulsecv",
        github: "https://github.com/mrkey2b/pulsecv",
        gitlab: "",
        gitea: "",
        nexus: "",
    },
    {
        id: "scpanel",
        name: "SCPanel Game",
        description:
            "Console d’administration unifiée pour orchestrer Pterodactyl, Pelican et Portainer avec gestion des instances, monitoring et contrôle des accès (RBAC).",
        image: "/img/sdpanel.png",
        previewVideo: "",
        status: "En Developpement",
        tags: [
            { name: "react", color: "text-blue-400" },
            { name: "nextjs16", color: "text-blue-400" },
            { name: "tailwind", color: "text-cyan-400" },
            { name: "nodejs", color: "text-green-400" },
            { name: "supabase", color: "text-green-400" },
            { name: "deploy", color: "text-pink-400" },
        ],
        live_link: "",
        source_code_link: "",
        github: "",
        gitlab: "",
        gitea: "",
        nexus: "",
    },
    {
        id: "mysanteweb",
        name: "MySanté Web",
        description:
            "Application de suivi santé avec dashboard temps réel, gestion multi-modules (vaccins, documents, métriques) et implémentation d’un RBAC complet.",
        image: "/img/mysanteweb.png",
        previewVideo: "",
        status: "En Developpement",
        tags: [
            { name: "react", color: "text-blue-400" },
            { name: "nextjs16", color: "text-blue-400" },
            { name: "tailwind", color: "text-cyan-400" },
            { name: "nodejs", color: "text-green-400" },
            { name: "supabase", color: "text-green-400" },
            { name: "deploy", color: "text-pink-400" },
        ],
        live_link: "",
        source_code_link: "",
        github: "",
        gitlab: "",
        gitea: "",
        nexus: "",
    },
    {
        id: "mysantemobile",
        name: "MySanté Mobile",
        description:
            "Application Android connectée à MySanté Web avec synchronisation temps réel des données (humeur, douleur, poids) et intégration complète avec le backend RBAC.",
        image: "/img/com.mrkey2b.mysante.jpg",
        previewVideo: "",
        status: "En Developpement",
        tags: [
            { name: "react native", color: "text-blue-400" },
            { name: "tailwind", color: "text-cyan-400" },
            { name: "nodejs", color: "text-green-400" },
            { name: "supabase", color: "text-green-400" },
            { name: "deploy", color: "text-pink-400" },
        ],
        live_link: "",
        source_code_link: "",
        github: "",
        gitlab: "",
        gitea: "",
        nexus: "",
    },
    {
        id: "vitrineclub77",
        name: "Club77 Vitrine",
        description:
            "Application web vitrine pour Club77 avec gestion des événements, contenus dynamiques (jobs, press, partenaires) et UI immersive orientée expérience.",
        image: "/img/club77.png",
        previewVideo: "",
        status: "En Developpement",
        tags: [
            { name: "react native", color: "text-blue-400" },
            { name: "nextjs16", color: "text-blue-400" },
            { name: "tailwind", color: "text-cyan-400" },
            { name: "nodejs", color: "text-green-400" },
            { name: "supabase", color: "text-green-400" },
            { name: "deploy", color: "text-pink-400" },
        ],
        live_link: "",
        source_code_link: "",
        github: "",
        gitlab: "",
        gitea: "",
        nexus: "",
    },
    {
        id: "erpclub77",
        name: "ERP Club77",
        description:
            "SaaS fullstack pour Club77 combinant dashboard de pilotage, intégration du site vitrine, monitoring technique et système RBAC complet.",
        image: "/img/erpclub77.png",
        previewVideo: "",
        status: "En Developpement",
        tags: [
            { name: "react native", color: "text-blue-400" },
            { name: "nextjs16", color: "text-blue-400" },
            { name: "tailwind", color: "text-cyan-400" },
            { name: "nodejs", color: "text-green-400" },
            { name: "supabase", color: "text-green-400" },
            { name: "deploy", color: "text-pink-400" },
        ],
        live_link: "",
        source_code_link: "",
        github: "",
        gitlab: "",
        gitea: "",
        nexus: "",
    },
    {
        id: "vitrineumami",
        name: "Umami Vitrine",
        description:
            "Site vitrine immersif pour Umami valorisant l’univers culinaire, les événements et l’identité visuelle du restaurant.",
        image: "/img/umami.png",
        previewVideo: "",
        status: "Archives",
        tags: [
            { name: "react", color: "text-blue-400" },
            { name: "nextjs16", color: "text-blue-400" },
            { name: "tailwind", color: "text-cyan-400" },
            { name: "nodejs", color: "text-green-400" },
            { name: "firebase", color: "text-red-400" },
            { name: "deploy", color: "text-pink-400" },
        ],
        live_link: "",
        source_code_link: "",
        github: "",
        gitlab: "",
        gitea: "",
        nexus: "",
    },
    {
        id: "erpumami",
        name: "ERP Umami",
        description:
            "Dashboard fullstack pour Umami intégrant monitoring, outils de debug, configuration système et contrôle des accès avancé (RBAC).",
        image: "/img/erpumami.png",
        previewVideo: "",
        status: "Archives",
        tags: [
            { name: "react", color: "text-blue-400" },
            { name: "nextjs16", color: "text-blue-400" },
            { name: "tailwind", color: "text-cyan-400" },
            { name: "nodejs", color: "text-green-400" },
            { name: "firebase", color: "text-red-400" },
            { name: "deploy", color: "text-pink-400" },
        ],
        live_link: "",
        source_code_link: "",
        github: "",
        gitlab: "",
        gitea: "",
        nexus: "",
    },
    {
        id: "app_panelCCR",
        name: "Game Panel CCROOM",
        description:
            "Panel de supervision temps réel pour réacteurs à fission et fusion dans un environnement de jeu moddé. Développé avec une interface moderne et un backend Lua sur serveurs ComputerCraft pour monitorer et piloter les systèmes énergétiques.",
        image: "/img/ccroom.png",
        previewVideo: "",
        status: "Déployé",
        tags: [
            { name: "react", color: "text-blue-400" },
            { name: "nextjs15", color: "text-blue-400" },
            { name: "tailwind", color: "text-cyan-400" },
            { name: "nodejs", color: "text-green-400" },
            { name: "deploy", color: "text-pink-400" },
        ],
        live_link: "https://ccroom.mrkey2b.fr",
        source_code_link: "https://github.com/mrkey2b/ccroom",
        github: "",
        gitlab: "https://github.com/mrkey2b/ccroom",
        gitea: "",
        nexus: "",
    },
    {
        id: "adpv4web",
        name: "ADP V4",
        description:
            "Application Web Gestion Serveurs de jeux",
        image: "/img/img404.png",
        previewVideo: "",
        status: "Archives",
        tags: [
            { name: "react", color: "text-blue-400" },
            { name: "tailwind", color: "text-cyan-400" },
            { name: "nodejs", color: "text-green-400" },
        ],
        live_link: "",
        source_code_link: "",
        github: "",
        gitlab: "",
        gitea: "",
        nexus: "",
    },
];

export default projects;