const projects = [
    {
        id: "portfolio",
        name: "Portfolio",
        description:
            "Portfolio personnel développé avec React, Vite et TailwindCSS.",
        image: "/img/portfolio.png",
        previewVideo: "/projects/portfolio-preview.mp4",
        status: "En ligne",
        tags: [
            { name: "react", color: "text-blue-400" },
            { name: "vite", color: "text-yellow-400" },
            { name: "tailwind", color: "text-cyan-400" },
        ],
        live_link: "https://mrkey2b.fr",
        source_code_link: "https://github.com/mrkey2b/mrkey2b.fr-portfolio",
        github: "https://github.com/mrkey2b/mrkey2b.fr-portfolio",
        gitlab: "",
        gitea: "",
        nexus: "",
    },
    {
        id: "pulsecv",
        name: "CV Builder ( PulseCV )",
        description:
            "Application Builder CV Custom",
        image: "/img/pulsecv.png",
        previewVideo: "",
        status: "Déployé",
        tags: [
            { name: "react", color: "text-blue-400" },
            { name: "nextjs16", color: "text-blue-400" },
            { name: "tailwind", color: "text-cyan-400" },
            { name: "nodejs", color: "text-green-400" },
            { name: "supabase", color: "text-green-400" },
            { name: "deploy", color: "text-pink-400" },
        ],
        live_link: "https://cv.mrkey2b.fr",
        source_code_link: "https://gitlab.com/ton-user/client-app",
        github: "",
        gitlab: "https://gitlab.com/ton-user/client-app",
        gitea: "",
        nexus: "",
    },
    {
        id: "scpanel",
        name: "SCPanel Game",
        description:
            "Une WebApp développé en react, qui a pour but de geré plusieurs sources, ( Pelican, Pterodactyl, Portainer )",
        image: "/img/lobbyapp.png",
        previewVideo: "",
        status: "En Developpement",
        tags: [
            { name: "react", color: "text-blue-400" },
            { name: "nextjs16", color: "text-blue-400" },
            { name: "tailwind", color: "text-cyan-400" },
            { name: "nodejs", color: "text-green-400" },
            { name: "supabase", color: "text-green-400" },
            { name: "deploy", color: "text-pink-400" },
        ],
        live_link: "",
        source_code_link: "",
        github: "",
        gitlab: "",
        gitea: "",
        nexus: "",
    },
    {
        id: "mysanteweb",
        name: "MySanté Web",
        description:
            "Une WebApp développé en react, qui a pour but de geré son dossier de santé éfficasement, ( elle es aussi lié a une application mobile (MySanté)",
        image: "/img/lobbyapp.png",
        previewVideo: "",
        status: "En Developpement",
        tags: [
            { name: "react", color: "text-blue-400" },
            { name: "nextjs16", color: "text-blue-400" },
            { name: "tailwind", color: "text-cyan-400" },
            { name: "nodejs", color: "text-green-400" },
            { name: "supabase", color: "text-green-400" },
            { name: "deploy", color: "text-pink-400" },
        ],
        live_link: "",
        source_code_link: "",
        github: "",
        gitlab: "",
        gitea: "",
        nexus: "",
    },
    {
        id: "mysantemobile",
        name: "MySanté Mobile",
        description:
            "Une Application Android développé en react native , qui a pour but de geré son dossier de santé éfficasement.",
        image: "/img/lobbyapp.png",
        previewVideo: "",
        status: "En Developpement",
        tags: [
            { name: "react native", color: "text-blue-400" },
            { name: "nextjs16", color: "text-blue-400" },
            { name: "tailwind", color: "text-cyan-400" },
            { name: "nodejs", color: "text-green-400" },
            { name: "supabase", color: "text-green-400" },
            { name: "deploy", color: "text-pink-400" },
        ],
        live_link: "",
        source_code_link: "",
        github: "",
        gitlab: "",
        gitea: "",
        nexus: "",
    },
    {
        id: "vitrineclub77",
        name: "Club77 Vitrine",
        description:
            "Une Application Android développé en react native , qui a pour but de geré son dossier de santé éfficasement.",
        image: "/img/lobbyapp.png",
        previewVideo: "",
        status: "En Developpement",
        tags: [
            { name: "react native", color: "text-blue-400" },
            { name: "nextjs16", color: "text-blue-400" },
            { name: "tailwind", color: "text-cyan-400" },
            { name: "nodejs", color: "text-green-400" },
            { name: "supabase", color: "text-green-400" },
            { name: "deploy", color: "text-pink-400" },
        ],
        live_link: "",
        source_code_link: "",
        github: "",
        gitlab: "",
        gitea: "",
        nexus: "",
    },
    {
        id: "lobbyapp",
        name: "LobbyAPP",
        description:
            "Application Web Lobby Gestion",
        image: "/img/lobbyapp.png",
        previewVideo: "",
        status: "Archives",
        tags: [
            { name: "react", color: "text-blue-400" },
            { name: "nextjs16", color: "text-blue-400" },
            { name: "tailwind", color: "text-cyan-400" },
            { name: "nodejs", color: "text-green-400" },
            { name: "supabase", color: "text-green-400" },
            { name: "deploy", color: "text-pink-400" },
        ],
        live_link: "",
        source_code_link: "https://gitlab.com/ton-user/client-app",
        github: "",
        gitlab: "https://gitlab.com/ton-user/client-app",
        gitea: "",
        nexus: "",
    },
    {
        id: "Landing",
        name: "Landing Demo",
        description:
            "Landing Page Demo Portfolio V2",
        image: "/img/folio2.png",
        previewVideo: "",
        status: "Archives",
        tags: [
            { name: "react", color: "text-blue-400" },
            { name: "nextjs16", color: "text-blue-400" },
            { name: "tailwind", color: "text-cyan-400" },
            { name: "nodejs", color: "text-green-400" },
            { name: "supabase", color: "text-green-400" },
            { name: "deploy", color: "text-pink-400" },
        ],
        live_link: "https://cv.mrkey2b.fr",
        source_code_link: "https://gitlab.com/ton-user/client-app",
        github: "",
        gitlab: "https://gitlab.com/ton-user/client-app",
        gitea: "",
        nexus: "",
    },
    {
        id: "app_panelCCR",
        name: "Game Panel CCROOM",
        description:
            "Application Web Gestion Control Room Nuclear Power Plant",
        image: "/img/ccroom.png",
        previewVideo: "",
        status: "Déployé",
        tags: [
            { name: "react", color: "text-blue-400" },
            { name: "nextjs16", color: "text-blue-400" },
            { name: "tailwind", color: "text-cyan-400" },
            { name: "nodejs", color: "text-green-400" },
            { name: "deploy", color: "text-pink-400" },
        ],
        live_link: "https://ccroom.mrkey2b.fr",
        source_code_link: "https://gitlab.com/ton-user/client-app",
        github: "",
        gitlab: "https://gitlab.com/ton-user/client-app",
        gitea: "",
        nexus: "",
    },
    {
        id: "lobbyapp",
        name: "LobbyAPP",
        description:
            "Application Web Lobby Gestion",
        image: "/img/lobbyapp.png",
        previewVideo: "",
        status: "Archives",
        tags: [
            { name: "react", color: "text-blue-400" },
            { name: "nextjs16", color: "text-blue-400" },
            { name: "tailwind", color: "text-cyan-400" },
            { name: "nodejs", color: "text-green-400" },
            { name: "supabase", color: "text-green-400" },
            { name: "deploy", color: "text-pink-400" },
        ],
        live_link: "https://cv.mrkey2b.fr",
        source_code_link: "https://gitlab.com/ton-user/client-app",
        github: "",
        gitlab: "https://gitlab.com/ton-user/client-app",
        gitea: "",
        nexus: "",
    },
];

export default projects;